### ISSUE TITLE
Could not parse the simulator list output

### ISSUE THREAD

**Issue by charliewang789** [dapx/bzaar#3]
Hello - i got following error, could you please help to figure out what's wrong?

D:\source\bzaar-master\bzaar-master>npx react-native run-ios
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - @shoutem/ui: http://shoutem.github.io/docs/ui-toolkit/introduction
  - react-native-code-push: https://microsoft.github.io/code-push
  - react-native-vector-icons: https://github.com/oblador/react-native-vector-icons
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Found Xcode project "bzaar.xcodeproj"
error Could not parse the simulator list output. Run CLI with --verbose flag for more details.
Error: spawnSync xcrun ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.execFileSync (child_process.js:642:13)
    at runOnSimulator (D:\source\bzaar-master\bzaar-master\node_modules\@react-native-community\cli-platform-ios\build\commands\runIOS\index.js:129:30)
    at Object.runIOS [as func] (D:\source\bzaar-master\bzaar-master\node_modules\@react-native-community\cli-platform-ios\build\commands\runIOS\index.js:97:12)
    at Command.handleAction (D:\source\bzaar-master\bzaar-master\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (D:\source\bzaar-master\bzaar-master\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (D:\source\bzaar-master\bzaar-master\node_modules\commander\index.js:651:12)
    at Command.parse (D:\source\bzaar-master\bzaar-master\node_modules\commander\index.js:474:21)

**Comment by dapx** [comment]
I think that this project is very out of date.
React native has changed too much.
I don’t believe that it will be interesting to run that, It will be very hard.
But if It is much needed I could try to help you.
Maybe I could help you on another way.
😅

**Comment by charliewang789** [comment]
Hi Daniel,

thank you for the reply.

I am very new to this, can you share me what would be the best next step?

i want to learn this and run it on iOS.

Charlie

**Comment by dapx** [comment]
I think that you should start from the [getting started](https://facebook.github.io/react-native/docs/0.60/getting-started)

Pay attention to select **React Native CLI Quickstart**.

That's where I have started.

**Comment by dapx** [comment]
I am very curious to know where do you are from.
I like so much talking with people from another country.

If you already read the getting started, I think you should go learning about routing the screens.
I recommend you start with [react-navigation](https://reactnavigation.org/docs/en/getting-started.html)

**Comment by charliewang789** [comment]
Thank you so much Daniel.

I am from Seattle, US. I guess we are far away from each other?

I will read through the two links you send out.

Charlie

**Comment by dapx** [comment]
Very nice!

Yeah, we are far away.
I am from Jaraguá do Sul, a small town in southern Brazil. 😄
